### ISSUE TITLE
Guest-Docker

### ISSUE THREAD

**Issue by ludeeus** [ludeeus/hass-config#34]
Start a guest docker container for HA when `switch.guest_mode` is on.
Stop it if its off.

**Comment by CCOSTAN** [comment]
What's this all about? Sounds cool..

**Comment by ludeeus** [comment]
@CCOSTAN Still just an idea, not sure how to implement it yet.
I will have 1 sleeper docker container with HA ready for when I have guests.

And either set up  shell_commands to run docker commands
or write a custom component for the portainer API.

**Comment by CCOSTAN** [comment]
I'm confused why your guests would need a different HA install?

**Comment by ludeeus** [comment]
I will not give them access to my own, they could have to much controll :)
But mostly because I can xD

**Comment by CCOSTAN** [comment]
aaah.. So just a cleaner interface.. Nice..

**Comment by ludeeus** [comment]
Inplemented in: [093543a](https://github.com/ludeeus/Home-Assistant-Config/commit/093543a147ac0693e59dbb7a74ca506d38a4dff0)
With the help of https://github.com/ludeeus/custom_component_hadockermon
